### ISSUE TITLE
Update openmrs after marking a child as deceased

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-server#299] opened 2017-07-19 10:56 UTC
Update openmrs patient's death date and deceased status after a child has been marked as deceased 
[Client Issue](https://github.com/OpenSRP/opensrp-client/issues/524)

**Comment by keymane** [comment] 2017-07-19 10:58
![screen shot 2017-07-17 at 11 30 22 am](https://user-images.githubusercontent.com/13656416/28363718-46725b0c-6c8a-11e7-8afd-4c323a0e6361.png)
![screen shot 2017-07-17 at 11 28 37 am](https://user-images.githubusercontent.com/13656416/28363719-4676e082-6c8a-11e7-878b-c9196ead85d9.png)

**Comment by cagulas** [comment] 2017-07-25 09:45
This looks good. Couple of points:

- [ ] Encounter date is showing incorrectly. I submitted report deceased encounter for dummy child Chipego Banda, ZEIR: 1217017. Encounter date should be today (July 25, 2017), but it's appearing as July 24, 2017 in OMRS test server, so it's a day off.
- [ ] Cause of death shows cause of death, see below:

![screen shot 2017-07-25 at 12 40 54 pm](https://user-images.githubusercontent.com/3488986/28566115-e0a8020c-7136-11e7-95da-e38bd625d90e.png)

Here is another view (fever is the cause of death and it's shown here, but cause of death is displayed twice):

![screen shot 2017-07-25 at 12 44 44 pm](https://user-images.githubusercontent.com/3488986/28566184-1025d02c-7137-11e7-9df1-ce23b4ce8738.png)

**Comment by ndegwamartin** [comment] 2017-08-04 06:35
The encounter date off by one error on the test server was found to be a timezone issue, however this should not be an issue on production

**Comment by cagulas** [comment] 2017-08-16 10:53
So what was the decision on the test server timezone issue? I submitted another report deceased form, and the date is still a day off. The test server is set to EST, but I don't understand why that would be a day off, because I submitted the form around noon London time, which is well past midnight for EST.

**Comment by cagulas** [comment] 2017-08-31 07:33
We won't fix the remaining issue regarding encounter date for now. The reason this is happening is because the time captured is 00:00, and the test server is in a different timezone (EST) than the app (CAT), so when the encounter gets added to the server, it is converted to EST.

We're adding a new issue to capture the time with the encounter: https://github.com/OpenSRP/opensrp-client-path/issues/12.

**Closed by cagulas** 2017-08-31 07:33 UTC
