### ISSUE TITLE
Update OMRS after report deceased form has been submitted 

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-server#292] opened 2017-07-13 13:52 UTC
Update OPENMRS  attribute/concept after report deceased form highlighted in https://github.com/OpenSRP/opensrp-client/issues/524 is saved

**Comment by cagulas** [comment] 2017-08-16 10:54
Duplicate of https://github.com/OpenSRP/opensrp-server/issues/299, closing.

**Closed by cagulas** 2017-08-16 10:54 UTC
