### ISSUE TITLE
Extend openmrs connector to include scheduling data

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-server#68] opened 2015-07-16 11:49 UTC

**Comment by ndisha** [comment] 2015-09-03 07:01
@maimoonak worked on the data format for the schedules data:
the schedule
when it is due
when it was fulfilled
what is the status
what was action
who was the receiver of this action
when it was closed
what is next to this

Alisa added the following comments:
- the schedule (type & trigger event) 
- when it is due (trigger date)
- when it was fulfilled (completion)
- what is the status (due, overdue, given)
- what was action (service provided or schedule edited)
- who was the receiver of this action (client ID) 
- who was the provider of this action (User ID) 
- when it was closed (expiry date & reason for expiration of schedule other action/close/moved etc) 
- what is next to this - what do you mean by this?

Also, if any edits to the schedule are made (ie. manual deletion of schedule for a particular patient) would be good to track this. 

For analytics - we will be interested in being able to track numbers of services delivered on time & also pull out cohorts of people that are overdue or nearly overdue and target them with a SMS reminder (these will need to pull info from Schedule, Status & Client ID).

For reporting - we will want to make use of all of these indicators/data also.

@sohelsarder @julkarnain @cagulas @koros @dimasciput 
Just flagging this format out, does it work for Bangladesh as well? @maimoonak  would like to finish on this.

**Comment by sohelsarder** [comment] 2015-09-03 07:22
@ndisha these will cover Bangladesh requirements as well, but one items i would like to add, with each schedule data we need to keep trace of its parent schedule reference to browse the total hierarchy of the events.

**Comment by ndisha** [comment] 2015-09-03 08:29
@maimoonak the question that Alisa raised on, what is next to this, would that be the flow that would then give us the hierarchy that @sohelsarder is asking for? For example, if the completion of a schedule action is movement to another register, that history can be traced at whatever point?

Please clarify or add the item on the list.

**Comment by cagulas** [comment] 2015-09-03 13:04
Just wanted to flag that the trigger date is NOT when the service is due.  The trigger date is the date that is used to trigger the schedule.  For example, polio 1 vaccine service schedule is triggered when a child is born; hence, the trigger date is the child's birth date, and it is used to calculate the due date.  The due date is: child's birth date + 6 wks.  Hope that makes sense.  It's small, but important difference.

Also, to give an idea of the types of indicators science teams may want to calculate for service schedules, pls see [this spreadsheet](https://docs.google.com/spreadsheets/d/1SGJmvjJAXMuY6cLJg0i9bYsgEXUtlp9vgzNwpRa7f3U/edit#gid=2) that was created for Dristhi.  For example:

Indicator 1: On time ANC1
Definition: Of those ANC women who received ANC1 service this month, what proportion was done on time (yellow/blue reminder)?

Indicator 2: Late ANC1
Definition: Of those ANC women who received ANC1 service this month, what proportion was done late (red reminder)?

Indicator 3: Missed ANC1
Definition: Number of women who missed ANC1 this month (reminder expires).

Hope this helps.

**Comment by maimoonak** [comment] 2015-09-03 18:18
Below is the complete info of available data in OpenSRP for scheduling and alerts. OpenMRS may require multiple tables for handling the data.
The data available can answer following

- the schedule (type & trigger event)  
 - (scheduleName & milestone)
- when it is due (trigger date)   
 - (referenceDate)
- when it was fulfilled (completion) 
 - (fulfillmentDate, completionDate)
- what is the status (due, overdue, given)  
 - (alertStatue and EnrollmentStatus)
- what was action (service provided or schedule edited) 
 - (I doubt whether its available or not. Also Schedule can not be edited.)
- who was the receiver of this action (client ID) 
 - (beneficiaryId)
- who was the provider of this action (User ID) 
 - (anmIdentifier/providerId)
- when it was closed (expiry date & reason for expiration of schedule other action/close/moved etc)  
 - two types available- alertClosed i.e. completed and Enrollment closed i.e. beneficiary case closed.
- what is next to this - 
 - Sohel wanted this but I doubt if its available. We can track hierarchy by dates and schedule names though.

@cagulas The indicator data is not covered in this scheduling part. One can calculate the indicators from encounter data and scheduling data. We can do it via Reporting once scheduling data is made available in OpenMRS..

<table>
  <tr>
    <th>Entity<br></th>
    <th>Property<br></th>
    <th>Possible Values<br></th>
    <th>Proposed Field Name in OpenMRS<br></th>
  </tr>
  <tr>
    <td>Action</td>
    <td>-</td>
    <td>-</td>
    <td></td>
  </tr>
  <tr>
    <td>Action</td>
    <td>anmIdentifier</td>
    <td>provider uuid or username<br></td>
    <td>providerId<br></td>
  </tr>
  <tr>
    <td>Action</td>
    <td>caseID</td>
    <td>beneficiary uuid<br></td>
    <td>beneficiaryId<br></td>
  </tr>
  <tr>
    <td>Action</td>
    <td>data</td>
    <td>allowed to add custom but predefined via ActionData<br></td>
    <td>listed below<br></td>
  </tr>
  <tr>
    <td>Action.data</td>
    <td>beneficiaryType</td>
    <td>register entities (mother, child, ec)<br></td>
    <td>beneficiaryType</td>
  </tr>
  <tr>
    <td>Action.data<br></td>
    <td>scheduleName</td>
    <td>schedule name specified in JSON health schedules. (ANC Visit/ lab reminder etc)<br></td>
    <td>scheduleName<br></td>
  </tr>
  <tr>
    <td>Action.data</td>
    <td>visitCode</td>
    <td>any milestone of specified schedule in JSON.(ANC1/ANC2/ANC3/)<br></td>
    <td>milestone</td>
  </tr>
  <tr>
    <td>Action.data</td>
    <td>alertStatus</td>
    <td>upcoming, normal, urgent, inProcess, complete</td>
    <td>alertStatus</td>
  </tr>
  <tr>
    <td>Action.data</td>
    <td>startDate</td>
    <td>startDate of milestone of specified schedule<br></td>
    <td>alertStartDate</td>
  </tr>
  <tr>
    <td>Action.data</td>
    <td>expiryDate</td>
    <td>expiryDate of milestone of specified schedule</td>
    <td>alertExpiryDate</td>
  </tr>
  <tr>
    <td>Action.data</td>
    <td>completionDate</td>
    <td>completionDate of milestone OR  schedule (weird but closing alert generates a separate Record)<br></td>
    <td>alertCompletionDate</td>
  </tr>
  <tr>
    <td>Action.data</td>
    <td>reasonForClose</td>
    <td>reasonForClose of beneficiary not milestone (weird but generates new Record)</td>
    <td>alertCloseReason</td>
  </tr>
  <tr>
    <td>Action.data [Action.actionTarget =report]</td>
    <td>annualTarget</td>
    <td>ignore for now<br></td>
    <td>-<br></td>
  </tr>
  <tr>
    <td>Action.data [Action.actionTarget =report]</td>
    <td>monthlySummaries</td>
    <td>ignore for now<br></td>
    <td>-</td>
  </tr>
  <tr>
    <td>Action</td>
    <td>actionTarget</td>
    <td>alert, report<br></td>
    <td>-</td>
  </tr>
  <tr>
    <td>Action</td>
    <td>actionType</td>
    <td>createAlert, closeAlert, close, <br>indicator [actionTarget=report]<br></td>
    <td>alertActionType</td>
  </tr>
  <tr>
    <td>Action</td>
    <td>isActionActive</td>
    <td>true, false (alerts marked as inactive on unenrolling beneficiary from schedule)<br></td>
    <td>isAlertActive</td>
  </tr>
  <tr>
    <td>Action</td>
    <td>timeStamp</td>
    <td>alert/action creation time<br></td>
    <td>alertCreationDate</td>
  </tr>
  <tr>
    <td>Action</td>
    <td>details</td>
    <td>did not find the usage anywhere<br></td>
    <td>additionalNote<br></td>
  </tr>
  <tr>
    <td>EnrollmentRecord</td>
    <td>externalId</td>
    <td>beneficiary uuid<br></td>
    <td>beneficiaryId (used to connect Action with Schedule)<br></td>
  </tr>
  <tr>
    <td>EnrollmentRecord</td>
    <td>scheduleName</td>
    <td>schedule name in JSON<br></td>
    <td>scheduleName (used to connect Action with Schedule)</td>
  </tr>
  <tr>
    <td>EnrollmentRecord</td>
    <td>preferredAlertTime</td>
    <td>preferred time configured by properties file<br></td>
    <td>preferredTime</td>
  </tr>
  <tr>
    <td>EnrollmentRecord</td>
    <td>referenceDateTime</td>
    <td>trigger date<br></td>
    <td>referenceDate</td>
  </tr>
  <tr>
    <td>EnrollmentRecord</td>
    <td>enrollmentDateTime</td>
    <td>date on which beneficiary enrolled<br></td>
    <td>enrollmentDate</td>
  </tr>
  <tr>
    <td>EnrollmentRecord</td>
    <td>startingMilestoneName</td>
    <td>starting milestone incase earlier ones are missed or skipped<br></td>
    <td>enrollmentMilestone</td>
  </tr>
  <tr>
    <td>EnrollmentRecord</td>
    <td>earliestStart</td>
    <td>earliest window start datetime of current milestone<br></td>
    <td>currentMilestoneEarliestStart</td>
  </tr>
  <tr>
    <td>EnrollmentRecord</td>
    <td>dueStart</td>
    <td>due window start datetime of current milestone</td>
    <td>currentMilestoneDueStart</td>
  </tr>
  <tr>
    <td>EnrollmentRecord</td>
    <td>lateStart</td>
    <td>late window start datetime of current milestone</td>
    <td>currentMilestoneLateStart</td>
  </tr>
  <tr>
    <td>EnrollmentRecord</td>
    <td>maxStart</td>
    <td>max window start datetime of current milestone</td>
    <td>currentMilestoneMaxStart</td>
  </tr>
  <tr>
    <td>Enrollment</td>
    <td>startOfSchedule</td>
    <td>trigger date (not confirmed)<br></td>
    <td>referenceDate</td>
  </tr>
  <tr>
    <td>EnrollmentRecord</td>
    <td>currentMilestoneName</td>
    <td>milestone under process at the moment<br></td>
    <td>currentMilestone</td>
  </tr>
  <tr>
    <td>Enrollment</td>
    <td>status</td>
    <td>ACTIVE, DEFAULTED, COMPLETED, UNENROLLED</td>
    <td>enrollmentStatus</td>
  </tr>
  <tr>
    <td>EnrollmentRecord</td>
    <td>metadata</td>
    <td>not used anywhere<br></td>
    <td>-</td>
  </tr>
  <tr>
    <td>Enrollment. MilestoneFulfillment</td>
    <td>fulfillments</td>
    <td>milestones fulfilled for specified schedule<br></td>
    <td>-</td>
  </tr>
  <tr>
    <td>MilestoneFulfillment</td>
    <td>milestoneName</td>
    <td>milestone name in fulfilled milestone list<br></td>
    <td>milestoneName</td>
  </tr>
  <tr>
    <td>MilestoneFulfillment</td>
    <td>fulfillmentDateTime</td>
    <td>milestone fulfillment date in fulfilled milestone list</td>
    <td>milestoneFulfillmentDate</td>
  </tr>
</table>

**Comment by maimoonak** [comment] 2015-09-03 18:42
Thanks Carolyn. This is very important point to keep in mind when designing
system and I wasn't aware of it. I would like to mention one thing that is
there is difference between the scheduling data and reporting requirements
of indicators. Means that scheduling component would allow access to all
data regarding scheduling including all types of timestamps, group info ,
beneficiaries, providers etc. But the indicator info is generated from
person event data and scheduling data. It is helpful for us to understand
the requirements clearly but scheduling will not be based on indicators.
Let me share our understanding of system in next email... then you can
provide your input on whether it fulfills all reporting requirements...

**Comment by cagulas** [comment] 2015-09-03 18:45
Thanks @maimoonak.  Understood.  I just wanted to share that in a comment, so we're aware of likely reporting needs to make sure all data that we need for reporting needs is covered in the connector module.  From your response, it seems like everything is covered.  Thx.

**Comment by maimoonak** [comment] 2015-09-04 14:47
Attached is the diagram of identified entities for OpenMRS scheduler tracker.
Since this is priority the scheduletracker would be data store only with REST API.
In next phase it would be refined further for scheduling capacity in OpenMRS.

![opensrpschedulingopenmrsclassdia](https://cloud.githubusercontent.com/assets/4829880/9686408/5a6cdeec-533d-11e5-8f05-c7beef1c37ca.png)

**Comment by maimoonak** [comment] 2015-09-12 14:07
@sohelsarder @julkarnain @ndisha  the basic arch of schedule data syncing added with completed schedules pushed to openmrs. The functionality although needs detailed testing and more work but can be used to test response to different schedules and to get an idea of hat type of changes you may need to merge in your branch. 
The functionality is NOT usable in field at the moment. Please test and provide your feedback. The openmrs side omod link is below
https://drive.google.com/a/ihsinformatics.com/file/d/0BzS8x1-rizzKOWxVYk5fbHlpdFU/view?usp=sharing
and opensrp branch is https://github.com/OpenSRP/opensrp-server/tree/81connectorExtend_mk

Two days of more dedicated work can make the module in stable and releaseable state. Hopefully, by next week we can get it fully done and tested.

**Comment by sohelsarder** [comment] 2015-09-13 04:59
@maimoonak thats a excellent initiative, it is understandable some changes required for different schedule requirements. Please let us know while minimal viable things  ready for check we would merge then with our branch and send you our observations.

**Comment by maimoonak** [comment] 2015-09-18 06:29
@sohelsarder The pull request has been created for the work done. Please test code for your branch. I have added test cases for HH data and as well as different scenarios too.
Steps to make it work.
- Download omod from link provided.
- Upload OR Clean and reupload if already exists on server
- Upload Your Json schedule on openmrs schedule tracker from UI.
- Merge with your branch and run war file
- Should push all new schedules to OpenMRS or Log error in error-tracker module.
- NOTE: Old schedules would be ignored.

**Comment by sohelsarder** [comment] 2015-09-20 12:25
Thanks for these hard works, I have some quick questions to reconfirm my understanding the steps you asked to follow,


    Download omod from link provided --- i can't download omod, i think you need to allow me permission there.
    Upload OR Clean and reupload if already exists on server --- is this mean upload that omod file  into openmrs module directory to install that module.
    Upload Your Json schedule on openmrs schedule tracker from UI.---- i think after 1&2 it will clear, just a quick check did you install that openmrs module in ona openmrs instance and i can quick check that UI?
    Merge with your branch and run war file--- you mean merging with branch 81connectorExtend_mk?
    Should push all new schedules to OpenMRS or Log error in error-tracker module.
    NOTE: Old schedules would be ignored.

**Comment by maimoonak** [comment] 2015-09-21 04:22
@sohelsarder 
- I have re-configured sharing settings. It should be accessible now.
- Yes, it should be uploaded to OpenMRS as a module
- No, I have not uploaded it on Ona dev server yet. Once we merge it with master and have got BD team`s feedback it would be uploaded to dev server along with latest opensrp-web
- Yes, code is in this branch i.e 81connectorExtend_mk

**Comment by ndisha** [comment] 2015-10-05 09:32
@sohelsarder, did you manage to install and test the schedules module? Have you done any end to end test from the OpenSRP client side? Any feedback? 

@numeranazneen any observations on this?

**Comment by sohelsarder** [comment] 2015-10-05 10:45
@ndisha We did not reach openmrs part yet, but we merged the changes and checking whether earlier functional part still working as well with modified forms and  after merging of several changes from different branch.

**Comment by maimoonak** [comment] 2015-11-10 06:35
#84 Done!!

**Closed by maimoonak** 2015-11-10 06:35 UTC
Labels: High Priority
